### ISSUE TITLE
Rewrite from jersey-client to plain java and remove jersey dependency

### ISSUE THREAD

**Issue by sherriff** [Cantara/Whydah-Java-SDK#20]
1. jersey-client may cause conflicts in applications which also use jersey. Decide what to do and implement. 
The most flexible (best?) solution is perhaps to stop using jersey-client and reimplement using plain java. As far as I can see almost all commands use the jersey-client, so this is some work...  

2. rxjava is a transitive (runtime) dependency of Hystrix. It is also overridden and set to different scope and version than hystrix use. 
2a. Can it use the same version as hystrix? 
2b. Is it only used by tests? If so, can test scope be used?

**Comment by sherriff** [comment]
@totto: Comment on rxjava?

**Comment by totto** [comment]
Rxjava is explicit override as of a bug in Hystrix

**Comment by totto** [comment]
We have started a side-by-side repacement approach of commands, starting with CommandLogonApplication (where the old command is CommandLogonApplicationjersey) - we should complete this transformation in all commands and re-test everything before we remove the *Jersey command copies and the dependency
