### ISSUE TITLE
Add Role to existing User

### ISSUE THREAD

**Issue by baardl** [Cantara/Whydah-Java-SDK#6]

**Comment by totto** [comment]
Limitation of which applications the calling application can add roles to

**Comment by baardl** [comment]
The calling application may only add roles to the same application, none
else.

**Comment by totto** [comment]
Not really correct...  it could add roles to a set of applications, i.e. all sub-applications of a solution...  example...   a software factory admin application should have access to add roles to the build, repo, test++  applications

**Comment by totto** [comment]
the access control is done in the backend services and not in the convenience API in the SDK

**Comment by baardl** [comment]
Definition on which application and user the role will be added to, is set in UserRole.
